{{- if eq .Values.configSecret.existingSecret "" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vault-unseal.fullname" . }}-conf
  labels:
    {{- include "vault-unseal.labels" . | nindent 4 }}
  {{- with .Values.configSecret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
stringData:
  vault-unseal.yaml:
    {{- with .Values.configSecret.stringData }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
