on:
  push:
    tags:
      - '*'

jobs:
  gh-release:
    name: gh-release
    runs-on: ubuntu-latest
    steps:
      - uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }}
